heat_template_version: 2015-04-30
description: Simple template to deploy a single streamsets data colloector
parameters:
  image:
    type: string
    description: Image used for servers
  flavor:
    type: string
    description: Flavor used by the servers
  key:
    type: string
    description: SSH key to connect to the servers
  security_group_name:
    type: string
    description: Security group used by the servers
  private_net:
    type: string
    description: Network used by the servers
  public_net:
    type: string
    description: Public IP used by the servers
resources:
  my_streamsets:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      key_name: { get_param: key }
      flavor: { get_param: flavor }
      networks:
      - network: { get_param: private_net }
      security_groups:
      - get_param: security_group_name
      user_data: |
        #!/bin/bash
        ulimit -n 32768
        /etc/streamsets-datacollector-3.4.0/bin/streamsets dc

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: public_net}

  floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: {get_resource: floating_ip}
      server_id: {get_resource: my_streamsets}
